add_newline = true

[aws]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold green)"

[cmd_duration]

[conda]

[directory]
truncation_length = 3

[dotnet]
disabled = true

[env_var]
disabled = true

[git_branch]
symbol = " "

[git_commit]
disabled = false
commit_hash_length = 4
tag_symbol = '  '

[git_state]
disabled = true

[git_status]
conflicted = "=${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "\\$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[gcloud]
disabled = true

[golang]
symbol = " "

[hostname]

[jobs]

[kubernetes]
symbol = "☸ "
style = "blue bold"
disabled = true

[line_break]
disabled = false

[lua]
symbol = " "
lua_binary = "luajit"

[nix_shell]
disabled = true

[memory_usage]
disabled = true

[julia]

[nim]

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[terraform]
symbol = " "
format = "via [$symbol$version]($style)"

[time]
disabled = true

[username]
disabled = false
